Backend auth
koukunwlk/ft_transcendence pull request #1
Opened 2023-12-12 16:01 UTC by rgenge

Authentication working( some parts are hard coded that will connect later on with user)
Added some variables in user

2023-12-12 17:00 UTC, willianportilho approved these changes

2023-12-14 23:39 UTC, koukunwlk requested changes

2023-12-14 23:39 UTC, koukunwlk commented on backend/.env
> +NEST_API_CLIENT_ID="u-s4t2ud-941b73c259f6d553c86a6684f13a7532d9ee7991657547ad9e0e69ec1a37f16d"
please, add the env file to the gitignore

2023-12-14 23:39 UTC, koukunwlk commented on backend/src/auth/42-auth/42.strategy.service.ts
> +    console.log(secret)
remove the log

2023-12-14 23:39 UTC, koukunwlk commented on backend/src/auth/42-auth/42.strategy.service.ts
> +    console.log(this.userService.getUser('acosta-a'))
remove this too

2023-12-14 23:39 UTC, koukunwlk commented on backend/src/auth/auth.controller.ts
> +const teste = new User({
After doing all your tests, you need to remove all unnecessary code to ensure the code quality

2023-12-14 23:39 UTC, koukunwlk commented on backend/src/auth/auth.controller.ts
> +    private authService: AuthService,
you must inject the services to use with nestjs feature

2023-12-14 23:39 UTC, koukunwlk commented on backend/src/auth/auth.controller.ts
> +    console.log('2fa Secret Generated');
remove

2023-12-14 23:39 UTC, koukunwlk commented on backend/src/auth/auth.controller.ts
> +    console.log(tfa.secret);
remove

2023-12-14 23:39 UTC, koukunwlk commented on backend/src/auth/auth.controller.ts
> +    const tfa = await this.authService.generateTfaSecret(user.props.userId);
From hexagonal architecture, the controller cannot have our business logic, so we put the logic on a service and make all the necessary validations and return it for the controller

2023-12-14 23:39 UTC, koukunwlk commented on backend/src/auth/auth.controller.ts
> +    console.log('testando verify:', req.user);
remove

2023-12-14 23:39 UTC, koukunwlk commented on backend/src/auth/auth.service.ts
> +    @Inject(USER_REPOSITORY_TOKEN)
Why are you using a symbol as token?

2023-12-14 23:39 UTC, koukunwlk commented on backend/src/user/repository/user-typeorm.repository.ts
> +      token: user.getToken(),
In the user model, create a function called toEntity that returns all fields to use like a object

like
```ts
class UserModel {
 private props: UserProps
 
 
 toEntity() {
  return this.props
 }
}

```

2024-01-20 15:14 UTC, merged